### ISSUE TITLE
Nomic's Solidity VSCode plugin support

### ISSUE THREAD

**Issue by jtakalai** [frangio/hardhat-ignore-warnings#2]
Would be really nice if this plugin would silence also the warnings generated by Nomic's Solidity plugin, see https://marketplace.visualstudio.com/items?itemName=NomicFoundation.hardhat-solidity

<img width="887" alt="Screenshot 2023-02-07 at 15 36 56" src="https://user-images.githubusercontent.com/16594664/217259840-7f383eda-b824-4733-976c-4de35058d46c.png">

(wonky indent because I wanted to show both the tooltip and the ignore line ;)

I have the plugin enabled in hardhat.config.ts, and I'm not getting the warning when I run `hardhat compile`.

**Comment by frangio** [comment]
This is an interesting request but you should open an issue in the [hardhat-vscode](https://github.com/NomicFoundation/hardhat-vscode) repo. It's not something I would be able to implement in this plugin as far as I can tell.
