### ISSUE TITLE
Inline Comments don't seem to work

### ISSUE THREAD

**Issue by quiet-node** [frangio/hardhat-ignore-warnings#5]
```solidity 
 function reassign() pure public returns (uint) {
        uint x = 1;
        {
            x = 2; // this will assign to the outer variable

            // solc-ignore-next-line shadowing
            uint x;
        }
        return x; // x has value 2
    }
```

When compile even with the inline comment to ignore the warning, this warning below will still be thrown

```bash
Warning: This declaration shadows an existing declaration.
  --> contracts/solidity/scoping/Scoping.sol:23:13:
   |
23 |             uint x;
   |             ^^^^^^
Note: The shadowed declaration is here:
  --> contracts/solidity/scoping/Scoping.sol:18:9:
   |
18 |         uint x = 1;
   |         ^^^^^^

```

Above is just an example for the `shadowing` ID, it doesn't seem to work with any other IDs ("unsued-var, "unused-param", etc.)

**Comment by frangio** [comment]
This may be due to CRLF line endings. There was a problem with inline comments that has now been fixed in https://github.com/frangio/hardhat-ignore-warnings/commit/e9e032747c4d671c466411d4c9c5a54fb475f408 and published in the last release. Please see if this has fixed it.
